# Generated by Django 2.1 on 2018-08-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.CharField(max_length=30)),
                ('pur_price', models.IntegerField()),
                ('pur_date', models.DateTimeField(blank=True, null=True)),
                ('sell_qty', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('sell_date', models.DateTimeField(blank=True, null=True)),
                ('profit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
