# Generated by Django 2.1 on 2018-08-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='pur_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='sell_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
